/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 wave.gltf 
Author: saurabh.buradkar7 (https://sketchfab.com/saurabh.buradkar7)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/waving-hand-sign-f1207a2ef0324b2d9df432975939628e
Title: Waving Hand Sign
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/wave.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
          scale={6}
          geometry={nodes.Object_4.geometry} material={materials['YellowMetallic.1814']} position={[0.635, 0, -0.342]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/wave.gltf')
